---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/roles":
    get:
      summary: list roles
      responses:
        '200':
          description: successful
    post:
      summary: create role
      responses:
        '200':
          description: successful
  "/api/v1/roles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show role
      responses:
        '200':
          description: successful
    patch:
      summary: update role
      responses:
        '200':
          description: successful
    put:
      summary: update role
      responses:
        '200':
          description: successful
    delete:
      summary: delete role
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
